/*
Each new term in the Fibonacci sequence is generated by adding the previous 
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;

public class ID2{
	public static void main(String[] args) {
		List<Integer> fibs = new ArrayList<Integer>();
		fibs.add(1);
		fibs.add(2);

		int value = 0;
		int counter = 1;
		while(value < 4000000) {
			value = fibs.get(counter) + fibs.get(counter-1);
			
			fibs.add(value);
			counter++;
		}
		
		Iterator<Integer> iterator = fibs.iterator();

		int sumOfEvenValue = 0;
		while(iterator.hasNext()) {
			int nextValue = iterator.next();
			if(nextValue % 2 == 0) {
				System.out.println(nextValue);
				sumOfEvenValue += nextValue;
			}
		}

		System.out.println(" Sum of Even Value : " + sumOfEvenValue);
	}
}